---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - rm -rf molecule/resources/provisioning
  - ansible --version
  - molecule --version
  - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning

variables:
  GET_SOURCES_ATTEMPTS: "5"

Ansible lint:
  stage: lint
  before_script:
    - ansible --version
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - ansible-lint --version
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

Docker java-8:
  stage: deployment test
  script:
  - molecule test -s default
  tags:
  - aws

AWS java-6:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-6
  tags:
    - aws

AWS java-7:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-7
  tags:
    - aws

AWS java-8:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-8
  tags:
    - aws

AWS java-8 Windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-8
  tags:
    - aws

AWS java-11:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-11
  tags:
    - aws

AWS java-11 Windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-11
  tags:
    - aws

AWS java-12:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-12
  tags:
    - aws

AWS java-12 Windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-12
  tags:
    - aws

EPC java-8:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated
