---
# Run all tests
stages:
  - lint
  - deployment test

before_script:
  - rm -rf molecule/resources/provisioning
  - ansible --version
  - ansible-lint --version
  - molecule --version
  - git clone https://github.com/lean-delivery/ansible-molecule-drivers.git molecule/resources/provisioning

variables:
  GET_SOURCES_ATTEMPTS: "5"

Lint:
  stage: lint
  before_script:
    - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules
  script:
    - yamllint . -c .yamllint
    - ansible-lint . -c .ansible-lint
  after_script:
    - rm -rf ~/ansible-lint-rules
  tags:
    - aws

Docker java-on-defaults:
  stage: deployment test
  script:
  - molecule test -s default
  tags:
  - aws

AWS java-6:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-6
  tags:
    - aws

.AWS java-7:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-7
  tags:
    - aws

AWS java-8:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-8
  tags:
    - aws

AWS java-8 Windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-8
  tags:
    - aws

AWS openjdk-13 Windows chocolatey:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-openjdk13-chocolatey
  tags:
    - aws

.AWS java-11:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-11
  tags:
    - aws

AWS openjdk-8:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-openjdk-8
  tags:
    - aws

AWS openjdk-11:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-openjdk-11
  tags:
    - aws

AWS openjdk-12:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-openjdk-12
  tags:
    - aws

AWS openjdk-ga:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-openjdk-ga
  tags:
    - aws

AWS openjdk-ga Windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-openjdk-windows-ga
  tags:
    - aws

.AWS java-11 Windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-11
  tags:
    - aws

AWS java-12:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-direct-12
  tags:
    - aws

AWS java-12 Windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-12
  tags:
    - aws

AWS sapjvm-8:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-sapjvm-8
  tags:
    - aws

AWS sapjvm-8 Windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-sapjvm-8
  tags:
    - aws

AWS zulu-12:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-zulu-12
  tags:
    - aws

AWS zulu-12 Windows:
  image: leandelivery/docker-ansible-ci:ansible-2.7
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-zulu-12
  tags:
    - aws

AWS zulu-12 Windows chocolatey:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-windows-zulu12-chocolatey
  tags:
    - aws

EPC java-8:
  variables:
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc-delegated
  tags:
    - delegated

AWS adoptopenjdk-8:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-adoptopenjdk-8
  tags:
    - aws

AWS adoptopenjdk-11:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-adoptopenjdk-11
  tags:
    - aws

AWS adoptopenjdk-12:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-adoptopenjdk-12
  tags:
    - aws

AWS adoptopenjdk Windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-adoptopenjdk-windows
  tags:
    - aws

AWS sapmachine-10:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-sapmachine-10
  tags:
    - aws

AWS sapmachine-11:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-sapmachine-11
  tags:
    - aws

AWS sapmachine-12:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-sapmachine-12
  tags:
    - aws

AWS sapmachine-13:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-sapmachine-13
  tags:
    - aws

AWS sapmachine-windows:
  variables:
    AWS_REGION: us-east-1
  stage: deployment test
  script:
    - molecule test -s cloud-aws-sapmachine-windows
  tags:
    - aws
