---
dist: xenial
sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - git clone https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

install:
  - pip install --upgrade ansible==2.7.* docker-py molecule==2.20 pyOpenSSL PyYAML pytest
  - pip install git+https://github.com/ansible/ansible-lint.git
  - ansible --version
  - ansible-lint --version

script:
  - yamllint . -c .yamllint
  - ansible-lint . -c .ansible-lint
  - molecule test -s default

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
