---
- name: "Install {{ java_package }} from chocolatey"
  win_chocolatey:
    name: "{{ java_package }}{{ java_major_version }}"
    params: "/InstallationPath:C:\\Program Files\\Java /Force /Machine"
  when: transport == "win-chocolatey"

- name: "Non-chocolatey installation"
  block:

    - name: "Path to the remote installation package"
      set_fact:
        java_artifact: "{{ windows_temp_path }}\
{{ oracle_artifact | win_basename }}"

    - name: "Copy installation package to the remote"
      win_copy:
        src: "{{ oracle_artifact }}"
        dest: "{{ java_artifact }}"

    - name: "Install package from the remote source"
      win_package:
        path: "{{ java_artifact }}"
        state: "present"
        creates_path: "C:\\Program Files\\Java"
        arguments: "/s"

    - name: "Get installed java directory"
      win_shell: "Get-ChildItem -Path 'C:\\Program Files\\Java' |\
                  Select-Object -Last 1 -ExpandProperty FullName"
      register: java_folder
      failed_when: not java_folder.stdout_lines[0]
      changed_when: False

    - name: "Set java environment variable"
      win_environment:
        name: "JAVA_HOME"
        state: "present"
        value: "{{ java_folder.stdout_lines[0] }}"
        level: "machine"

    - name: "Ensure that 'JAVA_HOME/bin' present in 'Path' variable"
      win_path:
        elements: "{{ java_folder.stdout_lines[0] }}\\bin"
        state: "present"
        scope: "machine"

  when: transport != "win-chocolatey"
