---
- name: Download artifact from s3
  aws_s3:
    bucket: '{{ transport_s3_bucket }}'
    object: '{{ transport_s3_path }}'
    dest: '{{ download_path }}/{{ transport_s3_path | basename }}'
    aws_access_key: '{{ transport_s3_aws_access_key }}'
    aws_secret_key: '{{ transport_s3_aws_secret_key }}'
    mode: get
    overwrite: different
    ignore_nonexistent_bucket: True
  retries: 5
  delay: 2

- name: Set downloaded artifact var
  set_fact:
    java_artifact_s3: '{{ download_path }}/{{ transport_s3_path|basename }}'
