---
- name: Add repository for AdoptOpenJDK
  yum_repository:
    name: AdoptOpenJDK
    description: AdoptOpenJDK
    baseurl: "http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/\
              {{ rh_dist_repo_version }}/x86_64"
    enabled: true
    gpgcheck: true
    gpgkey: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

- name: Install java packages
  yum:
    name: '{{ (transport == "repositories") | ternary(jdk_package, java_artifact) }}'
    state: present
  register: package_install
  until: package_install is succeeded
