---
- name: Check choco
  win_chocolatey:
    name: chocolatey
    state: present

# Workaround for new chocolatey output.
# See https://github.com/ansible/ansible/issues/53860#issuecomment-473431360 for more details
#- name: disable enhanced exit codes
#  win_chocolatey_feature:
#    name: useEnhancedExitCodes
#    state: disabled

- name: Debug hoco_package
  debug:
    var: choco_java_package

- name: 'Install {{ choco_java_package }} from chocolatey'
  win_chocolatey:
    name: '{{ choco_java_package }}'
  register: choco_install
  retries: 15
  delay: 5
  until: choco_install is succeeded

- name: Debug choco_install
  debug:
    var: choco_install
