---
- name: Artifact stored localy
  set_fact:
    java_artifact: '{{ transport_local }}'
    java_artifact_basename: '{{ transport_local | basename }}'

- name: Split artifact name
  set_fact:
    parts: >-
      {{ java_artifact_basename |
      regex_findall('^(.*j[dkre]{2})-([0-9]+)[u.]([0-9.]+)[-_]([a-z]+)-(x64|i586)') |
      first | list }}

- name: Set variables based on split
  set_fact:
    java_package: '{{ parts[0][-3:] }}'
    java_major_version: '{{ parts[1] }}'
    java_minor_version: '{{ parts[2] }}'
    java_os: '{{ parts[3] }}'
    java_arch: '{{ parts[4] }}'

- name: Copy artifact to destination
  copy:
    src: '{{ java_artifact }}'
    dest: '{{ download_path }}'
  register: file_downloaded
  retries: 5
  delay: 2
  until: file_downloaded is succeeded

- name: Downloaded artifact
  set_fact:
    java_artifact: '{{ file_downloaded.dest }}'
