---
- name: "Artifact stored localy"
  set_fact:
    oracle_artifact: "{{ transport_local }}"
    oracle_artifact_basename: "{{ oracle_artifact | basename }}"

- name: "Getting java version variables"
  set_fact:
    java_package: "{{ oracle_artifact_basename.split('-')[0] }}"
    java_major_version: "{{ oracle_artifact_basename.split('-')[1].split('u')[0] }}"
    java_minor_version: "{{ oracle_artifact_basename.split('-')[1].split('u')[1] }}"
    java_arch: "{{ oracle_artifact_basename.split('-')[3] }}"
