---
- name: Download security policy artifact from Oracle OTN
  get_url:
    url: '{{ fallback_oracle_security_policy_artifacts[java_major_version|int] }}'
    dest: '{{ download_path }}'
    mode: 0755
    headers:
      Cookie: >-
        gpw_e24=http%3A%2F%2Fwww.oracle.com%2F;
        oraclelicense=accept-securebackup-cookie;
        --no-check-certificate
  register: file_downloaded
  retries: 15
  delay: 5
  until: "'OK' in file_downloaded.msg"

- name: Downloaded security policy artifact
  set_fact:
    security_policy_oracle_artifact: '{{ file_downloaded.dest }}'
