---
- name: Fetch download page
  win_uri:
    url: "{{ adoptopenjdk_api_page }}\
      info/releases/\
      openjdk{{ java_major_version }}\
      ?openjdk_impl={{ adoptopenjdk_impl }}\
      &os=windows&\
      arch={{ (java_arch == 'x64') | ternary('x64', 'x32') }}\
      &release=latest\
      &type={{ java_package }}&heap_size=normal"
    return_content: true
    follow_redirects: all
  register: download_page

- name: Find release url
  set_fact:
    release_url: >-
      {{ (download_page.content | from_json).binaries | map(attribute='binary_link') | list +
        (download_page.content | from_json).binaries | map(attribute='checksum_link') | list }}

- name: Exit if AdobtOpenJDK version is not found
  fail:
    msg: 'AdoptOpenJDK version {{ java_major_version }} not found'
  when: release_url[0] is not defined

- name: 'Fetch artifact checksum file {{ release_url[1] }}'
  win_uri:
    url: '{{ release_url[1] }}'
    return_content: true
  register: artifact_checksum_file

- name: 'Get artifact checksum from file {{ release_url[1] }}'
  set_fact:
    artifact_checksum:
      content: >-
        {{ artifact_checksum_file['content'] |
          regex_search('([^\s]+)')
        }}

- name: 'Download artifact from {{ release_url[0] }}'
  win_get_url:
    url: '{{ release_url[0] }}'
    dest: '{{ java_download_path }}'
    force: true
    checksum: '{{ artifact_checksum.content }}'
    checksum_algorithm: sha256
  register: file_downloaded
  retries: 20
  delay: 5
  until: file_downloaded is succeeded
