---
- name: 'Fetch download page'
  win_uri:
    url: "{{ adoptopenjdk_api_page }}\
      info/releases/\
      openjdk{{ java_major_version }}\
      ?openjdk_impl={{ adoptopenjdk_impl }}\
      &os=windows&arch=x64\
      &release=latest\
      &type={{ java_package }}&heap_size=normal"
    return_content: true
    follow_redirects: all
  register: download_page

- name: Find release url
  set_fact:
    release_url: >-
      {{ download_page['content'] |
      regex_findall('(https://github.com/AdoptOpenJDK/.*\.zip[.sha256.txt]*)')
      }}

- name: Exit if AdobtOpenJDK version is not found
  fail:
    msg: 'AdoptOpenJDK version {{ java_major_version }} not found'
  when: release_url[1] is not defined

- name: 'Get artifact checksum {{ release_url[1] }}'
  win_uri:
    url: '{{ release_url[1] }}'
    return_content: true
  register: artifact_checksum

- name: Set artifact basename
  set_fact:
    artifact_url: '{{ release_url[0] }}'
    artifact_basename: "{{ (release_url[0] | urlsplit('path')).split('/')[-1] }}"

- name: 'Get {{ checksum_alg }} checksum of file'
  win_stat:
    path: '{{ download_path }}\{{ artifact_basename }}'
    get_checksum: true
    checksum_algorithm: '{{ checksum_alg }}'
  register: artifact

- name: Download with checksum validation
  include_tasks: fetch_checksum.yml
  when: |
    not artifact.stat.exists
    or artifact.stat.checksum != artifact_checksum.content
  retries: 15
  delay: 2
  until: artifact.stat.checksum == artifact_checksum.content

- name: Set downloaded artifact vars
  set_fact:
    file_downloaded:
      dest: '{{ artifact.stat.path }}'