---
- name: Check requested major version for Corretto
  fail:
    msg: Supported versions of Amazon Corretto only 8 and 11
  when:
    - java_major_version|int != 8
    - java_major_version|int != 11

- name: Check requested architecture for Corretto
  fail:
    msg: Amazon Corretto currently supports x64 platform only
  when: java_arch != 'x64'

- name: 'Fetch root page {{ corretto_root_page }}'
  win_uri:
    url: '{{ corretto_root_page }}'
    return_content: true
  register: root_page

- name: Find release url
  set_fact:
    release_url: >-
      {{ root_page['content']
        | regex_search('(https://corretto.aws/downloads/latest/amazon-corretto-'
            ~ java_major_version ~ '-' ~ java_arch ~ '-windows-' ~ java_package ~'\.' ~ java_package_type ~')')
          }}
    release_checksum: >-
      {{ root_page['content']
        | regex_search('(https://corretto.aws/downloads/latest_checksum/amazon-corretto-'
            ~ java_major_version ~ '-' ~ java_arch ~ '-windows-' ~ java_package ~ '\.' ~ java_package_type ~')')
          }}

- name: 'Download artifact from {{ release_url }}'
  win_get_url:
    url: '{{ release_url }}'
    dest: '{{ java_download_path }}'
    checksum: >-
      {{ lookup('url', release_checksum) }}
    checksum_algorithm: md5
  register: file_downloaded
  retries: 20
  delay: 5
  until: file_downloaded is succeeded
