---
- name: Set java minor version
  set_fact:
    minor: "{{ java_minor_version | default('.*', true) }}"

- name: 'Fetch root page {{ java_root_page }}'
  win_uri:
    url: '{{ openjdk_root_page }}/{{ java_major_version }}/'
    return_content: true
    follow_redirects: all
  register: root_page

- name: Find release url
  set_fact:
    release_url: >-
      {{ root_page['content'] |
      regex_findall('(https://download[\.\w]+/java/GA/jdk' +
      java_major_version|string +
      '[.\d]+/[\d\w]+/' +
      java_major_version|string +
      '/GPL/openjdk-' +
      java_major_version|string +
      '[\d._]+windows-x64_bin[\w\d.]+)')
      }}

- name: Exit if OpenJDK version is not General-Availability Release
  fail:
    msg: 'OpenJDK version {{ java_major_version }} not GA Release, or maybe something wrong with java.net'
  when: release_url[1] is not defined

- name: 'Get artifact checksum {{ release_url[1] }}'
  win_uri:
    url: '{{ release_url[1] }}'
    return_content: true
  register: artifact_checksum

- name: Show artifact checksum
  debug:
    var: artifact_checksum.content

- name: Set artifact basename
  set_fact:
    artifact_url: '{{ release_url[0] }}'
    artifact_basename: "{{ (release_url[0] | urlsplit('path')).split('/')[-1] }}"

- name: Get SHA256 checksum of file
  win_stat:
    path: '{{ download_path }}\{{ artifact_basename }}'
    get_checksum: true
    checksum_algorithm: sha256
  register: artifact

- name: Download with checksum validation
  include_tasks: fetch_checksum.yml
  when: |
    not artifact.stat.exists
    or artifact.stat.checksum != artifact_checksum.content
  retries: 15
  delay: 2
  until: artifact.stat.checksum == artifact_checksum.content

- name: Downloaded artifact
  set_fact:
    java_artifact: '{{ artifact.stat.path }}'

- name: Split artifact name
  set_fact:
    parts: >-
      {{ java_artifact | win_basename
        | regex_findall('^(.*j[dkre]{2})-([0-9]+)[u.]([0-9.]+)[-_]([a-z]+)-(x64|i586)')
        | first | list }}

- name: Set variables based on split
  set_fact:
    java_package: '{{ parts[0][-3:] }}'
    java_major_version: '{{ parts[1] }}'
    java_minor_version: '{{ parts[2] }}'
    java_os: '{{ parts[3] }}'
    java_arch: '{{ parts[4] }}'
