---
- name: Download artifact from web
  win_get_url:
    url: '{{ transport_web }}'
    dest: >-
      {{ download_path }}\{{ (transport_web
          | urlsplit('path')).split('/')[-1] }}
    force: False
  register: file_downloaded
  retries: 5
  delay: 2
  until: "'OK' in file_downloaded.msg"

- name: Set downloaded artifact vars
  set_fact:
    oracle_artifact: '{{ file_downloaded.dest }}'
    oracle_artifact_basename: '{{ file_downloaded.dest | win_basename }}'

- name: Split artifact name
  set_fact:
    parts: >-
      {{ oracle_artifact_basename |
      regex_findall('^(.*j[dkre]{2})-([0-9]+)[u.]([0-9.]+)[-_]([a-z]+)-(x64|i586)') |
      first | list }}

- name: Set variables based on split
  set_fact:
    java_package: '{{ parts[0] }}'
    java_major_version: '{{ parts[1] }}'
    java_minor_version: '{{ parts[2] }}'
    java_os: '{{ parts[3] }}'
    java_arch: '{{ parts[4] }}'
